apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ex-clamav-server.fullname" . }}-db-secret
  labels:
    {{- include "ex-clamav-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "ex-clamav-server.databaseUrl" . | quote }}
